language: ruby

rvm:
  - 2.4.0
  - 2.3.0
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - rbx-2
  - jruby-19mode
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-head

sudo: false

bundler_args: --without=guard

notifications:
  disabled: true

script:
  - bundle exec rake
