language: ruby

rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - 2.2.10
  - 2.1.10
  - 2.0.0

before_install:
  - gem update --remote bundler
  - gem update --system

sudo: false

bundler_args: --without=guard

notifications:
  disabled: true

script:
  - bundle exec rake
